POST http://localhost:3003/api/blogs/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcnNvbiIsImlkIjoiNjYwZTk2MTBhZTZhOWI3YjM5ZjkyOThlIiwiaWF0IjoxNzEyMjM5MjY0fQ.w-cQR7-zmg46Oi1bnE-0rKOsAvBfYXCOs3xMUea3z2g

{
    "title": "Cybersecurity themes",
    "author": "Daniel Miessler",
    "url": "https://danielmiessler.com/",
    "likes": 3,
    "userId": "660e9610ae6a9b7b39f9298e"
}