POST http://localhost:3003/api/blogs/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcnNvbiIsImlkIjoiNjYxM2I4ZmVmMzVhZmIzMWRkNDBlNDc4IiwiaWF0IjoxNzEyNTY4NTk0fQ.UerOE5vIM-wQoYcanJqWemDLat4xYVYnM5eW9X--kMM

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 10,
    "userId": "6613b8fef35afb31dd40e478"
}